apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: insurance-platform

resources:
  - ../../base

images:
  - name: us-central1-docker.pkg.dev/sn-insurance-platform/claims-repo/claims-service
    newTag: v18
